# Generated by Django 2.2 on 2019-05-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieRecommendation', '0003_recommendationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movieBackdropURL',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='moviePosterURL',
            field=models.CharField(default='', max_length=200),
        ),
    ]
